package UI;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import Datenbank.Datenbank;
import Projekt.Projekt;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class StartFensterController {
	@FXML
	private Button btn_newProjekt;
	@FXML
	private TableView<Projekt> tbl_projektTabelle;
	@FXML
	private TableColumn<Projekt, String> tblCell_projektName;
	@FXML
	private TableColumn<Projekt, String> tblCell_projektErsteller;
	@FXML
	private TableColumn<Projekt, String> tblCell_projektStart;
	@FXML
	private TableColumn<Projekt, String> tblCell_projektEnd;
	@FXML
	private TableColumn tblCell_projektSend;
	@FXML
	private TextField txt_suche;
	@FXML
	private TextField txt_newProjekt_name;
	@FXML
	private TextField txt_newProjekt_ersteller;
	@FXML
	private CheckBox check_vorlage;
	@FXML
	private Button btn_suche;
	
	
	 Datenbank myDB = new Datenbank();
	 private ObservableList<Projekt> projektData;

	
	
	@FXML
    private void initialize() {
		System.out.println("Initalisierungs Methode startet automatisch");
		myDB.getProjekte();
	}

	// Event Listener on Button[#btn_newProjekt].onAction
	@FXML
	public void btn_newProjekt_click(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_suche].onAction
	@FXML
	public void btn_suche_click(ActionEvent event) {
		// TODO Autogenerated
	}
}
