package UI;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import Projekt.Projekt;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.Tab;

import javafx.scene.control.CheckBox;

import javafx.scene.control.TableColumn;

public class UebersichtFensterController {
	@FXML
	private Tab tab_Projekt;
	@FXML
	private TableColumn table_p1;
	@FXML
	private TableColumn table_P2;
	@FXML
	private Tab tab_Quartal;
	@FXML
	private TableColumn table_Q1;
	@FXML
	private TableColumn table_Q2;
	@FXML
	private Tab tab_Jahr;
	@FXML
	private TableColumn table_J1;
	@FXML
	private TableColumn table_J2;
	@FXML
	private CheckBox ckb_risiko;
	@FXML
	private Button btn_Export;
	@FXML
	private Button btn_zurueck;
	@FXML
	private Label lbl_Name;
	@FXML
	private Label lbl_Ersteller;
	@FXML
	private Label lbl_SDate;
	@FXML
	private Label lbl_EDate;
	@FXML
	private Label lbl_Meldestat;
	
	// Projekt
	private Projekt projekt;
	
	
	@FXML
	private void initialize() {
		
		projekt = OpenUebersichtPage.tmpProjekt;
		
		lbl_Name.setText(projekt.getName());
		lbl_Ersteller.setText(projekt.getErsteller());
		lbl_SDate.setText(projekt.getStartDate());
		lbl_EDate.setText(projekt.getEndDate());
		if (projekt.isAbgeschickt() == true) {
			lbl_Meldestat.setText("Projekt Gemeldet");
		} else {
			lbl_Meldestat.setText("Projekt nicht Gemeldet");
		}
	}

	// Event Listener on Button[#btn_Export].onAction
	@FXML
	public void btn_Export_click(ActionEvent event) {
		// TODO Autogenerated
	}
}
